# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with Puppeteer dependencies
FROM node:22-alpine AS builder

# Install necessary build tools
RUN apk add --no-cache make gcc g++ python3

# Create app directory
WORKDIR /app

# Copy project files to the working directory
COPY package.json tsconfig.json ./
COPY src ./src

# Install dependencies
RUN npm install

# Build the project
RUN npm run build

# Use a clean Node.js image for the final build
FROM node:22-alpine

WORKDIR /app

# Copy built files and node_modules from the builder
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json
COPY entrypoint.sh /app/entrypoint.sh

# Make entrypoint executable
RUN chmod +x /app/entrypoint.sh

# Expose the health check port
EXPOSE 3000

# Use entrypoint script that runs both health HTTP and MCP stdio
ENTRYPOINT ["/bin/sh", "/app/entrypoint.sh"]
